# Form implementation generated from reading ui file 'c:\Users\laiwa\wanqin\project\Arona\arona.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_arona(object):
    def setupUi(self, arona):
        arona.setObjectName("arona")
        arona.resize(800, 600)
        arona.setMinimumSize(QtCore.QSize(800, 600))
        arona.setMaximumSize(QtCore.QSize(800, 600))
        arona.setStyleSheet("QMainWindow {\n"
"    background-image: url(:/images/background.jpg);\n"
"    background-position: center;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=arona)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.area1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.area1.setMinimumSize(QtCore.QSize(40, 0))
        self.area1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.area1.setObjectName("area1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.area1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logButton = QtWidgets.QPushButton(parent=self.area1)
        self.logButton.setMinimumSize(QtCore.QSize(40, 80))
        icon = QtGui.QIcon.fromTheme("QIcon::ThemeIcon::DocumentProperties")
        self.logButton.setIcon(icon)
        self.logButton.setIconSize(QtCore.QSize(24, 24))
        self.logButton.setObjectName("logButton")
        self.verticalLayout.addWidget(self.logButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.area1)
        self.area2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.area2.setMinimumSize(QtCore.QSize(560, 0))
        self.area2.setMaximumSize(QtCore.QSize(560, 16777215))
        self.area2.setStyleSheet("QWidget#area2 {\n"
"    border: 2px solid #66CCFF;\n"
"}")
        self.area2.setObjectName("area2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.area2)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.logTextEdit = QtWidgets.QTextEdit(parent=self.area2)
        self.logTextEdit.setReadOnly(True)
        self.logTextEdit.setObjectName("logTextEdit")
        self.verticalLayout_2.addWidget(self.logTextEdit)
        self.horizontalLayout.addWidget(self.area2)
        self.area3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.area3.setMinimumSize(QtCore.QSize(200, 0))
        self.area3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.area3.setObjectName("area3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.area3)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.captureHandleButton = QtWidgets.QPushButton(parent=self.area3)
        self.captureHandleButton.setMinimumSize(QtCore.QSize(0, 35))
        self.captureHandleButton.setStyleSheet("QPushButton {\n"
"    background-color: #66CCFF;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #55BBEE;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44AADD;\n"
"}")
        self.captureHandleButton.setObjectName("captureHandleButton")
        self.horizontalLayout_2.addWidget(self.captureHandleButton)
        self.handleLineEdit = QtWidgets.QLineEdit(parent=self.area3)
        self.handleLineEdit.setMinimumSize(QtCore.QSize(80, 35))
        self.handleLineEdit.setMaximumSize(QtCore.QSize(80, 16777215))
        self.handleLineEdit.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #66CCFF;\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    background-color: white;\n"
"}")
        self.handleLineEdit.setReadOnly(True)
        self.handleLineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.handleLineEdit.setObjectName("handleLineEdit")
        self.horizontalLayout_2.addWidget(self.handleLineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.selectBgButton = QtWidgets.QPushButton(parent=self.area3)
        self.selectBgButton.setMinimumSize(QtCore.QSize(0, 35))
        self.selectBgButton.setStyleSheet("QPushButton {\n"
"    background-color: #66CCFF;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #55BBEE;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44AADD;\n"
"}")
        self.selectBgButton.setObjectName("selectBgButton")
        self.verticalLayout_3.addWidget(self.selectBgButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.startButton = QtWidgets.QPushButton(parent=self.area3)
        self.startButton.setMinimumSize(QtCore.QSize(0, 45))
        self.startButton.setStyleSheet("QPushButton {\n"
"    background-color: #66CCFF;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    font-size: 14pt;\n"
"    padding: 5px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #55BBEE;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #44AADD;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.verticalLayout_3.addWidget(self.startButton)
        self.horizontalLayout.addWidget(self.area3)
        arona.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=arona)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        arona.setMenuBar(self.menubar)

        self.retranslateUi(arona)
        QtCore.QMetaObject.connectSlotsByName(arona)

    def retranslateUi(self, arona):
        _translate = QtCore.QCoreApplication.translate
        arona.setWindowTitle(_translate("arona", "AronaAutoPat"))
        self.logButton.setText(_translate("arona", "执行\n"
"日志"))
        self.captureHandleButton.setText(_translate("arona", "抓取句柄"))
        self.selectBgButton.setText(_translate("arona", "选择背景图"))
        self.startButton.setText(_translate("arona", "启动"))
